// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/package2/package2.proto

package package2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Package2Request struct {
	StrKey               string   `protobuf:"bytes,1,opt,name=StrKey,proto3" json:"StrKey,omitempty"`
	StrKey2              string   `protobuf:"bytes,2,opt,name=StrKey2,proto3" json:"StrKey2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Package2Request) Reset()         { *m = Package2Request{} }
func (m *Package2Request) String() string { return proto.CompactTextString(m) }
func (*Package2Request) ProtoMessage()    {}
func (*Package2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca13334593c75b1, []int{0}
}

func (m *Package2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package2Request.Unmarshal(m, b)
}
func (m *Package2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package2Request.Marshal(b, m, deterministic)
}
func (m *Package2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package2Request.Merge(m, src)
}
func (m *Package2Request) XXX_Size() int {
	return xxx_messageInfo_Package2Request.Size(m)
}
func (m *Package2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Package2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Package2Request proto.InternalMessageInfo

func (m *Package2Request) GetStrKey() string {
	if m != nil {
		return m.StrKey
	}
	return ""
}

func (m *Package2Request) GetStrKey2() string {
	if m != nil {
		return m.StrKey2
	}
	return ""
}

func init() {
	proto.RegisterType((*Package2Request)(nil), "package2.Package2Request")
}

func init() { proto.RegisterFile("proto/package2/package2.proto", fileDescriptor_6ca13334593c75b1) }

var fileDescriptor_6ca13334593c75b1 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x35, 0x82, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x1c, 0x30, 0xbe, 0x92, 0x33, 0x17, 0x7f, 0x00, 0x94, 0x1d, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c,
	0x22, 0x24, 0xc6, 0xc5, 0x16, 0x5c, 0x52, 0xe4, 0x9d, 0x5a, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0xe5, 0x09, 0x49, 0x70, 0xb1, 0x43, 0x58, 0x46, 0x12, 0x4c, 0x60, 0x09, 0x18, 0x37,
	0x89, 0x0d, 0x6c, 0xaa, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xef, 0x49, 0xfa, 0x46, 0x76, 0x00,
	0x00, 0x00,
}
