// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/package2/package2.proto

package package2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	package1 "goprotodemo/proto/package1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Req struct {
	No                   string        `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PackageOneReq        *package1.Req `protobuf:"bytes,3,opt,name=packageOneReq,proto3" json:"packageOneReq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca13334593c75b1, []int{0}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *Req) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Req) GetPackageOneReq() *package1.Req {
	if m != nil {
		return m.PackageOneReq
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "demo.app.package2.Req")
}

func init() { proto.RegisterFile("proto/package2/package2.proto", fileDescriptor_6ca13334593c75b1) }

var fileDescriptor_6ca13334593c75b1 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x35, 0x82, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x82, 0x29, 0xa9, 0xb9, 0xf9, 0x7a, 0x89, 0x05, 0x05, 0x7a, 0x30, 0x09, 0x29, 0x54, 0x1d, 0x86,
	0x70, 0x06, 0x44, 0x87, 0x52, 0x3a, 0x17, 0x73, 0x50, 0x6a, 0xa1, 0x10, 0x1f, 0x17, 0x53, 0x5e,
	0xbe, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x5e, 0xbe, 0x90, 0x10, 0x17, 0x4b, 0x5e,
	0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x04, 0xcc, 0x16, 0xb2, 0xe1, 0xe2, 0x85, 0x6a, 0xf6, 0xcf,
	0x4b, 0x0d, 0x4a, 0x2d, 0x94, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd3, 0x43, 0xb7, 0xd4,
	0x50, 0x2f, 0x28, 0xb5, 0x30, 0x08, 0x55, 0xb1, 0x93, 0x4c, 0x94, 0x54, 0x7a, 0x3e, 0xd8, 0x4e,
	0x90, 0x72, 0x7d, 0x54, 0x7f, 0x24, 0xb1, 0x81, 0xf9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7f, 0xa6, 0x34, 0xa1, 0xe0, 0x00, 0x00, 0x00,
}
