// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/package1/package1.proto

package package1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Req struct {
	StrField             string   `protobuf:"bytes,1,opt,name=strField,proto3" json:"strField,omitempty"`
	IntField             int32    `protobuf:"varint,2,opt,name=intField,proto3" json:"intField,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_b71a452ec28794b2, []int{0}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetStrField() string {
	if m != nil {
		return m.StrField
	}
	return ""
}

func (m *Req) GetIntField() int32 {
	if m != nil {
		return m.IntField
	}
	return 0
}

func init() {
	proto.RegisterType((*Req)(nil), "demo.app.package1.Req")
}

func init() { proto.RegisterFile("proto/package1/package1.proto", fileDescriptor_b71a452ec28794b2) }

var fileDescriptor_b71a452ec28794b2 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x35, 0x84, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x82, 0x29, 0xa9, 0xb9, 0xf9, 0x7a, 0x89, 0x05, 0x05, 0x7a, 0x30, 0x09, 0x25, 0x5b, 0x2e, 0xe6,
	0xa0, 0xd4, 0x42, 0x21, 0x29, 0x2e, 0x8e, 0xe2, 0x92, 0x22, 0xb7, 0xcc, 0xd4, 0x9c, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x97, 0x99, 0x57, 0x02, 0x91, 0x63, 0x52,
	0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x9d, 0x64, 0xa2, 0xa4, 0xd2, 0xf3, 0xc1, 0x86, 0x83, 0x8c,
	0xd6, 0x47, 0xb5, 0x3e, 0x89, 0x0d, 0xcc, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x92, 0x52,
	0x12, 0x20, 0x97, 0x00, 0x00, 0x00,
}
