// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/package1/package1.proto

package package1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request1 struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	IntFiels             int32    `protobuf:"varint,2,opt,name=intFiels,proto3" json:"intFiels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request1) Reset()         { *m = Request1{} }
func (m *Request1) String() string { return proto.CompactTextString(m) }
func (*Request1) ProtoMessage()    {}
func (*Request1) Descriptor() ([]byte, []int) {
	return fileDescriptor_b71a452ec28794b2, []int{0}
}

func (m *Request1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request1.Unmarshal(m, b)
}
func (m *Request1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request1.Marshal(b, m, deterministic)
}
func (m *Request1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request1.Merge(m, src)
}
func (m *Request1) XXX_Size() int {
	return xxx_messageInfo_Request1.Size(m)
}
func (m *Request1) XXX_DiscardUnknown() {
	xxx_messageInfo_Request1.DiscardUnknown(m)
}

var xxx_messageInfo_Request1 proto.InternalMessageInfo

func (m *Request1) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Request1) GetIntFiels() int32 {
	if m != nil {
		return m.IntFiels
	}
	return 0
}

func init() {
	proto.RegisterType((*Request1)(nil), "package1.Request1")
}

func init() { proto.RegisterFile("proto/package1/package1.proto", fileDescriptor_b71a452ec28794b2) }

var fileDescriptor_b71a452ec28794b2 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x35, 0x84, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x1c, 0x30, 0xbe, 0x92, 0x0d, 0x17, 0x47, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0xa1, 0x90,
	0x08, 0x17, 0xab, 0x5b, 0x66, 0x6a, 0x4e, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84,
	0x23, 0x24, 0xc5, 0xc5, 0x91, 0x99, 0x57, 0x02, 0x62, 0x17, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xb0,
	0x06, 0xc1, 0xf9, 0x49, 0x6c, 0x60, 0xe3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x30, 0x30,
	0xc6, 0x35, 0x6f, 0x00, 0x00, 0x00,
}
